// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRD_FgI_6SC0G9K5SooF1-iklWNstw5kc',
    appId: '1:199450109077:web:a63cd35e04f122b12d679c',
    messagingSenderId: '199450109077',
    projectId: 'test-auth-flutter-flow',
    authDomain: 'test-auth-flutter-flow.firebaseapp.com',
    storageBucket: 'test-auth-flutter-flow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBpTxjXntSUi1GTxbHjHUnMlqSF4BAuWA',
    appId: '1:199450109077:android:2ba43d2338320a302d679c',
    messagingSenderId: '199450109077',
    projectId: 'test-auth-flutter-flow',
    storageBucket: 'test-auth-flutter-flow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RGudn1Bqfhpt_AVWIq0NgYzG6HXTMYs',
    appId: '1:199450109077:ios:181a3dff56ab0ba72d679c',
    messagingSenderId: '199450109077',
    projectId: 'test-auth-flutter-flow',
    storageBucket: 'test-auth-flutter-flow.appspot.com',
    iosClientId: '199450109077-710ddh7ga0md914vpklfigv0q0j9kk3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
